title: OpenDoc Template
remote_theme: opengovsg/opendoc-theme
timezone: Asia/Singapore
elastic_search:
  index: template
  doctype: bare
environment: DEV
section_order:
styling_options:
  primary_brand_color: '#444'
  logo_path: /assets/logo.png
